"""
Regenerate the manuscript's numeric table bodies from the results CSVs.

Writes LaTeX fragments (the rows between \\midrule and \\bottomrule) to
article_4/results/tables/, so every number appearing in a table of
article.tex is machine-regenerable from the experiment artifacts:

    eff_rank_saturated.tex   tab:eff-rank-sat      (E2)
    queue_exponents.tex      tab:queue-exponents   (E3)
    half_life.tex            tab:half-life         (E5)
    nonlinear.tex            tab:nonlinear         (E6)
    coefficients.tex         app:coefficients      (exact, from schemes.py)
    sensitivity.tex          tab:sensitivity       (E6s)

The fragments are compared against the hardcoded bodies in article.tex by
eye (or diff) when the manuscript is updated; captions and column headers
live in the manuscript.
"""

from __future__ import annotations

import csv
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
RESULTS = BASE / "results"
TABLES = RESULTS / "tables"

LINEAR_LABELS = {
    "uw1": "UW1", "lw": "LW", "bw": "BW", "fromm": "FR",
    "ub3": "UB3", "ub5": "UB5", "weno5l": "WENO5-LIN",
    "weno5l_rk3": "WENO5-LIN+SSP-RK3",
}
NONLINEAR_LABELS = {
    "muscl-minmod": "MUSCL minmod", "muscl-mc": "MUSCL MC",
    "muscl-vanleer": "MUSCL van Leer", "muscl-superbee": "MUSCL superbee",
    "weno5-js": "WENO5-JS", "weno5-m": "WENO5-M", "weno5-z": "WENO5-Z",
}


def _read(name: str) -> list[dict]:
    with (RESULTS / name).open() as f:
        return list(csv.DictReader(f))


def _write(name: str, lines: list[str]) -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    path = TABLES / name
    path.write_text("% generated by make_tables.py -- do not edit\n"
                    + "\n".join(lines) + "\n")
    print(f"  wrote {path.relative_to(BASE)}")


def _sci(v: float, digits: int = 3) -> str:
    mant, expo = f"{v:.{digits}e}".split("e")
    return f"${mant}\\times10^{{{int(expo)}}}$"


def table_eff_rank_saturated() -> None:
    rows = _read("effective_rank_saturated.csv")
    lam_cols = ["1.0", "0.9", "0.5", "0.1", "0.05", "0.01", "0.001"]
    lines = []
    for key, label in LINEAR_LABELS.items():
        if key == "weno5l_rk3":
            continue
        vals = {r["lambda"]: r["effective_rank"]
                for r in rows if r["scheme"] == key}
        if not vals:
            continue
        lines.append(f"{label:3s} & " + " & ".join(vals[c] for c in lam_cols)
                     + " \\\\")
    _write("eff_rank_saturated.tex", lines)


def table_queue_exponents() -> None:
    rows = _read("queue_conditioning_fits.csv")
    lines = []
    for key, label in LINEAR_LABELS.items():
        if key == "weno5l_rk3":
            continue
        cells = []
        for L in range(1, 6):
            r = next((x for x in rows
                      if x["scheme"] == key and x["L"] == str(L)), None)
            if r is None:
                break
            cells.append(f"{float(r['gamma_fit']):.2f} "
                         f"({int(float(r['gamma_predicted']))})")
        if cells:
            lines.append(f"{label:3s} & " + " & ".join(cells) + " \\\\")
    _write("queue_exponents.tex", lines)


def table_half_life() -> None:
    rows = _read("delayed_collisions.csv")
    per_scheme: dict[str, dict] = {}
    for r in rows:
        key = r["scheme"]
        if key not in per_scheme or int(r["t0"]) > int(per_scheme[key]["t0"]):
            per_scheme[key] = r
    # Local injectivity horizon T_loc = min{L : rho(L) = r-1} from E1c
    # (lambda-independent; read at lambda = 0.5, r = 6).
    tloc: dict[str, int] = {}
    for r in _read("local_observability.csv"):
        if r["r"] != "6" or r["lambda"] != "0.5":
            continue
        if int(r["local_rank"]) >= int(r["r"]) - 1:
            L = int(r["L"])
            if r["scheme"] not in tloc or L < tloc[r["scheme"]]:
                tloc[r["scheme"]] = L
    n12_uw1 = float(per_scheme["uw1"]["half_life_predicted"])
    lines = []
    for key, label in LINEAR_LABELS.items():
        if key == "weno5l":
            continue          # E5 uses the SSP-RK3 pairing, not FE
        r = per_scheme.get(key)
        if r is None:
            continue
        pred = float(r["half_life_predicted"])
        fit = float(r["half_life_fit_tail"])
        dagger = "\\,$^\\dagger$" if abs(fit - pred) / pred > 0.05 else ""
        ratio = pred / n12_uw1
        if ratio < 1.5:
            ret = "$1$"
        elif ratio < 1.0e4:
            ret = f"${round(ratio):,}$".replace(",", "{,}")
        else:
            sig3 = float(f"{ratio:.3g}")
            ret = f"${round(sig3):,}$".replace(",", "{,}")
        lines.append(f"{label} & {r['t0']} & {tloc[key]} & {_sci(pred)} & "
                     f"{_sci(fit)}{dagger} & {ret} \\\\")
    _write("half_life.tex", lines)


def table_nonlinear() -> None:
    tab = _read("nonlinear_ensembles.csv")
    lad = _read("nonlinear_rank_ladders.csv")

    def ladder(scheme, regime, eps, col, Ls):
        d = {int(r["L"]): r[col] for r in lad
             if r["scheme"] == scheme and r["regime"] == regime
             and r["eps"] == eps}
        return ",".join(d[L] for L in Ls)

    def gap(v: float) -> str:
        if v < 1e-13:
            return "$<\\!10^{-13}$"
        return _sci(v, 1)

    regime_titles = {
        "smooth": "smooth (monotone parent)",
        "extremum": "extremum (peak-centered parent)",
        "jump": "jump (flat plateau upstream of the discontinuity)",
    }
    lines = []
    for i, (regime, title) in enumerate(regime_titles.items()):
        if i:
            lines.append("\\midrule")
        lines.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\emph{{{title}}}}}\\\\")
        for key, label in NONLINEAR_LABELS.items():
            t5 = next(r for r in tab if r["scheme"] == key
                      and r["regime"] == regime and r["eps"] == "1e-05")
            t2 = next(r for r in tab if r["scheme"] == key
                      and r["regime"] == regime and r["eps"] == "0.01")
            Ls = [1, 2, 3, 4, 5]
            lines.append(
                f"{label} & {t5['nstar_deep']} & "
                f"{ladder(key, regime, '1e-05', 'rank_emp_lead', Ls)} & "
                f"{ladder(key, regime, '1e-05', 'rank_lin', Ls)} & "
                f"{ladder(key, regime, '1e-05', 'rank_emp_lead', [12])} & "
                f"{gap(float(t5['sigma6_over_sigma1_L5']))} & "
                f"{gap(float(t2['sigma6_over_sigma1_L5']))} \\\\")
    _write("nonlinear.tex", lines)


def _frac_tex(a) -> str:
    """Positive Fraction magnitude -> LaTeX (integer or \\tfrac)."""
    if a.denominator == 1:
        return str(a.numerator)
    return f"\\tfrac{{{a.numerator}}}{{{a.denominator}}}"


def _poly_tex(p) -> str:
    """Exact coefficient list (low-to-high in lambda) -> LaTeX polynomial."""
    terms = []
    for i, a in enumerate(p):
        if a == 0:
            continue
        mono = "" if i == 0 else ("\\lambda" if i == 1
                                  else f"\\lambda^{{{i}}}")
        mag = abs(a)
        coef = "" if (mag == 1 and mono) else _frac_tex(mag)
        body = f"{coef}{mono}" if mono else coef
        if not terms:
            terms.append(f"-{body}" if a < 0 else body)
        else:
            terms.append(f"{'-' if a < 0 else '+'} {body}")
    return " ".join(terms) if terms else "0"


def table_coefficients() -> None:
    """Appendix tables: exact coefficient polynomials c_s(lambda).

    Machine-generated from schemes.coeff_polys / schemes.weno5l_rk3_polys
    (exact rational arithmetic) so no coefficient is transcribed by hand
    (REVISION_1 m1).  Three blocks: the semi-Lagrangian family (+ Fromm),
    the WENO5-LIN flux-difference operator with forward Euler, and the
    composed WENO5-LIN+SSP-RK3 one-step operator.
    """
    import schemes as sch

    labels = {"uw1": "UW1", "lw": "LW", "bw": "BW", "fromm": "FR",
              "ub3": "UB3", "ub5": "UB5"}
    lines = ["% --- semi-Lagrangian family + Fromm: Scheme & s & c_s ---"]
    for idx, name in enumerate(labels):
        polys = sch.coeff_polys(name)
        if idx:
            lines.append("\\midrule")
        for row, s in enumerate(sorted(polys, reverse=True)):
            lead = labels[name] if row == 0 else ""
            lines.append(f"{lead} & ${s}$ & ${_poly_tex(polys[s])}$ \\\\")

    lines.append("% --- WENO5-LIN flux difference + forward Euler (display body) ---")
    polys = sch.coeff_polys("weno5l")
    parts = [f"c_{{{s}}}={_poly_tex(polys[s])}"
             for s in sorted(polys, reverse=True)]
    lines.append(",\\quad\n".join(parts))

    lines.append("% --- WENO5-LIN + SSP-RK3 composed operator: s & c_s & s & c_s ---")
    polys = sch.weno5l_rk3_polys()
    ss = sorted(polys, reverse=True)
    half = len(ss) // 2
    for a, b in zip(ss[:half], ss[half:]):
        lines.append(f"${a}$ & ${_poly_tex(polys[a])}$ & "
                     f"${b}$ & ${_poly_tex(polys[b])}$ \\\\")

    _write("coefficients.tex", lines)


def table_sensitivity() -> None:
    """tab:sensitivity: one-at-a-time deviations from the E6s baseline.

    Summarizes results/nonlinear_sensitivity.csv (REVISION_1 m4): for
    each axis setting, the number of the 21 (scheme, regime) cells whose
    leading-floor ladder rho(1..5) or horizon-12 rank differs from the
    axis baseline, and the largest |change| in rho(12).  For the FD-step
    axis the compared columns hold the linearized ladders.
    """
    rows = _read("nonlinear_sensitivity.csv")
    tab = {(r["axis"], r["setting"], r["scheme"], r["regime"]):
           (tuple(r[f"rank{i}"] for i in range(1, 6)), r["rank12"])
           for r in rows}
    base = {"floor": "0.001", "M": "400", "seed": "0",
            "eps": "1e-05", "fd_delta": "1e-05"}
    cells = sorted({(r["scheme"], r["regime"]) for r in rows})

    def pow_tex(st: str) -> str:
        expo = round(__import__("math").log10(float(st)))
        return f"$10^{{{expo}}}$"

    axes = [
        ("floor", r"rank floor $\theta$", ["0.01", "0.0001"], pow_tex),
        ("M", r"ensemble size $M$", ["100", "200", "800"], str),
        ("seed", "seed", ["1", "2"], str),
        ("fd_delta", r"FD step $\delta$ (linearized)",
         ["0.0001", "1e-06"], pow_tex),
        ("eps", r"amplitude $\varepsilon$",
         ["0.01", "0.001", "1e-07"], pow_tex),
    ]
    lines = []
    for axis, label, settings, fmt in axes:
        for i, st in enumerate(settings):
            ch_lad = ch_12 = max_d12 = 0
            for sc, rg in cells:
                lad, r12 = tab[(axis, st, sc, rg)]
                lad0, r12_0 = tab[(axis, base[axis], sc, rg)]
                ch_lad += lad != lad0
                ch_12 += r12 != r12_0
                max_d12 = max(max_d12, abs(int(r12) - int(r12_0)))
            lines.append(f"{label if i == 0 else ''} & {fmt(st)} & "
                         f"{ch_lad} & {ch_12} & {max_d12} \\\\")
        if axis != axes[-1][0]:
            lines.append("\\addlinespace")
    _write("sensitivity.tex", lines)


def main() -> None:
    print("make_tables: regenerating LaTeX table bodies")
    table_eff_rank_saturated()
    table_queue_exponents()
    table_half_life()
    table_nonlinear()
    table_coefficients()
    table_sensitivity()


if __name__ == "__main__":
    main()
